### PR TITLE
Chore: bump dependency versions

### PR DESCRIPTION
**Pull request by Barabazs**
Hi @bastibe, I bumped the versions to the latest available.
Here's the output of the GH job: https://github.com/Barabazs/libsndfile-binaries/actions/runs/4044125281

I noticed that the filenames in the scripts are different than the actual filenames in the repo.
Do you want me to change this in the script?

### CODE REVIEW

**Comment by bastibe** [comment]
Awesome! Thank you!

At first I thought this was still building v1.1.0 on Windows, since that's what VCPKG lists on their website, but it seems it downloaded and compiled the v1.2.0 source code. Weird.

If you'd like to rename the files automatically, I'd be grateful for the help. Rebuilding is a pretty infrequent occurrence, though, so it's not a big deal really.

**Comment by Barabazs** [comment]
> At first I thought this was still building v1.1.0 on Windows, since that's what VCPKG lists on their website, but it seems it downloaded and compiled the v1.2.0 source code. Weird.

Yes, that is odd... FWIW I have checked the version of the dll and it outputs 1.2.0.

<details>
<summary>
For future reference:
 </summary>

`strings -el libsndfile_*bit.dll | egrep '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'`

  </details>

> If you'd like to rename the files automatically, I'd be grateful for the help. Rebuilding is a pretty infrequent occurrence, though, so it's not a big deal really.

I'll try to that one of these days. 

I have now uploaded the new binaries, except for ARM, as I don't have such a device and there is no GH runner that supports this platform.

**Comment by bastibe** [comment]
Thank you so much!

I haven't checked out the files themselves, but it looks like you might have swapped the Windows 64 and 32 bit binaries, on account of one growing by just the number of bytes the other one shrank.

**Comment by Barabazs** [comment]
> Thank you so much!
> 
> I haven't checked out the files themselves, but it looks like you might have swapped the Windows 64 and 32 bit binaries, on account of one growing by just the number of bytes the other one shrank.

Sorry about that. I've pushed the correct files now.

**Comment by bastibe** [comment]
> Sorry about that. I've pushed the correct files now.

No problem 😊. 

I'm planning to try the new libraries tomorrow. I'll merge this once I've tried them.

**Pull request merged**
