### PR TITLE
add macos arm64 build

### PR DESCRIPTION
**Pull request by faroit**
* [x] add dylib built locally
* [x] remove `--enable-werror` from script

### CODE REVIEW

**Comment by bastibe** [comment]
Brilliant! Thank you so much!

**Comment by bastibe** [comment]
A user in https://github.com/bastibe/python-soundfile/issues/325 just reported that the M1 binary you provided seems to lack MP3 support. Did you compile it from [the version of mac_build.sh from the 1.1.0 branch](https://github.com/bastibe/libsndfile-binaries/blob/bastibe/1.1.0-build/mac_build.sh)?

And might I ask once more for your help compiling an M1 binary for 1.1.0 with MP3 support?

**Comment by faroit** [comment]
> A user in https://github.com/bastibe/python-soundfile/issues/325 just reported that the M1 binary you provided seems to lack MP3 support. Did you compile it from [the version of mac_build.sh from the 1.1.0 branch](https://github.com/bastibe/libsndfile-binaries/blob/bastibe/1.1.0-build/mac_build.sh)?

yes, i did. But u just wanted to be quick and didn't test the build. Will get into it now

**Comment by faroit** [comment]
```
checking for lame/lame.h... no
checking for library containing lame_set_VBR_q... no
configure: WARNING: "MPEG support selected but external Lame library cannot be found.
checking for libmpg123 >= 1.25.10 ... yes

configure: WARNING: *** MPEG support disabled.

checking processor clipping capabilities... none
```

found it. 

@bastibe @adrian-stepien

**Comment by faroit** [comment]
I think this was addressed here: https://github.com/libsndfile/libsndfile/pull/822

**Comment by faroit** [comment]
@bastibe @adrian-stepien 

1. wait for the next release?
2. modify this repo to install from github source?
3. do 1. but me or adrian build just binaries locally and push them to this pr?

**Comment by bastibe** [comment]
Thank you for looking into this!

Is this somehow M1 specific? It seems that the CI build on macOS/intel does not seem to run into this issue for whatever reason: https://github.com/bastibe/libsndfile-binaries/runs/6469425537?check_suite_focus=true

I'd be in favor of building a patched library now, and possibly deploy an update once the fix is published upstream.

But please do not feel pressured or rushed to do this super quickly. The next release of soundfile has been in the works for several months, and it can wait a little longer, I'm sure. Open source should be fun, not stress!

**Comment by faroit** [comment]
I tried a bunch of things but i can't make configure finding the lame headers. @adrian-stepien maybe you have more luck

**Comment by faroit** [comment]
@bastibe You have more ideas now make configure find the lame headers?

**Comment by bastibe** [comment]
Honestly, I have no idea. Could you post the output of the mac_build.sh script? Perhaps a path changed or something...

**Pull request merged**
