### PR TITLE
adds compile script and CI job for building a manylinx-64 library

### PR DESCRIPTION
**Pull request by bastibe**

### CODE REVIEW

**Comment by polinaeterna** [comment]
hi @bastibe ! thank you for working on it! is there a plan to continue this PR? we would love to use `pysoundfile` with new`libsndfile` in [our library](https://github.com/huggingface/datasets). can we maybe help here somehow?

**Comment by bastibe** [comment]
Work on this is ongoing in #20. 

Be aware that PySoundFile is severely outdated and deprecated. Please use soundfile.

**Comment by bastibe** [comment]
Now I need your help! 

We now have up-to-date libsndfile binaries for Windows 32/64, Linux 64, and macOS 64. However, we are not yet able to compile macOS ARM64 binaries in the Github CI.

Could someone help me compile a ARM macOS libsndfile?

Essentially, you would need to check out [mac_build.sh](https://github.com/bastibe/libsndfile-binaries/blob/master/mac_build.sh), run it, and make the compiled libsndfile.dylib available to me in a pull request.

Once I have that, I can cut a new release of soundfile.

**Comment by lhoestq** [comment]
I just tried quickly and got
```
[ 92%] Building C object CMakeFiles/sndfile.dir/src/ALAC/ag_enc.c.o
[ 93%] Building C object CMakeFiles/sndfile.dir/src/ALAC/dp_enc.c.o
[ 94%] Building C object CMakeFiles/sndfile.dir/src/ALAC/dp_dec.c.o
[ 95%] Building C object CMakeFiles/sndfile.dir/src/ALAC/matrix_dec.c.o
make[2]: *** No rule to make target `/Users/hf/quentin/libsndfile-binaries/libvorbis-1.3.7/lib/.libs/libvorbisenc.a', needed by `libsndfile.1.0.35.dylib'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 96%] Building C object CMakeFiles/sndfile.dir/src/ALAC/matrix_enc.c.o
[ 97%] Building C object CMakeFiles/sndfile.dir/src/ALAC/alac_encoder.c.o
[ 98%] Building C object CMakeFiles/sndfile.dir/src/ALAC/alac_decoder.c.o
make[1]: *** [CMakeFiles/sndfile.dir/all] Error 2
make: *** [all] Error 2
cp: libsndfile-1.2.0/libsndfile.dylib: No such file or directory
chmod: libsndfile.dylib: No such file or directory
```
apparently this could be because libvorbis can't use libogg:
```
*** Could not run Ogg test program, checking why...
*** The test program compiled, but did not run. This usually means
*** that the run-time linker is not finding Ogg or finding the wrong
*** version of Ogg. If it is not finding Ogg, you'll need to set your
*** LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf to point
*** to the installed location  Also, make sure you have run ldconfig if that
*** is required on your system
***
*** If you have an old version installed, it is best to remove it, although
*** you may also be able to get things to work by modifying LD_LIBRARY_PATH
configure: error: must have Ogg installed!
make: *** No targets specified and no makefile found.  Stop.
```
make for libogg returned
```
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
make[2]: Nothing to be done for `all'.
Making all in include
Making all in ogg
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all-am'.
Making all in doc
Making all in libogg
make[3]: Nothing to be done for `all'.
make[3]: Nothing to be done for `all-am'.
```
using
- macOS 12.4
- Darwin 21.5.0 arm64

**Comment by lhoestq** [comment]
Got it to work by adding the `arm64` argument, and opened a PR at https://github.com/bastibe/libsndfile-binaries/pull/22

**Pull request merged**
