### PR TITLE
Add linux arm64 binary

### PR DESCRIPTION
**Pull request by azuwis**

### CODE REVIEW

**Comment by bastibe** [comment]
Awesome! Thank you!

Could you point me to your build script so I can borrow the build parameters for our own CI?

**Comment by azuwis** [comment]
I've just used https://github.com/bastibe/libsndfile-binaries/blob/master/linux_build.sh to build it on a linux arm64 VM.

**Comment by azuwis** [comment]
See https://github.com/bastibe/libsndfile-binaries/pull/24 for github CI job.

**Comment by bastibe** [comment]
That's fantastic! Thank you so much for your efforts!

**Comment by azuwis** [comment]
Please note that the binary in this PR is built on a VM of my local machine, not the one build in github CI.

**Comment by bastibe** [comment]
Thank you for the heads-up. I'll replace the binary for the wheel, then.

**Pull request merged**
