### PR TITLE
Build script improvements

### PR DESCRIPTION
**Pull request by bemoody**
A few small changes to make the build scripts behave more predictably.

- set the script interpreter

- if any command fails, the script should fail

- don't assume pkg-config is installed

### CODE REVIEW

**Comment by bemoody** [comment]
I don't really know what I'm doing, but I've tried to update the workflow to use the "manylinux_2_28" container from https://github.com/pypa/manylinux in place of the old CentOS 7 one.

Let's see if it works?

**Comment by bemoody** [comment]
It looks like the manylinux_2_28 build is okay.

But it sounds like `macos-11` is no longer available:
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal

It probably makes sense to switch Intel builds to use `macos-13` and arm64 to `macos-14`.  (I'm guessing since mac_build.sh sets MACOSX_DEPLOYMENT_TARGET, that means the binaries should be backward-compatible?)

It looks like there are some other build problems on Windows, unfortunately.

**Comment by bemoody** [comment]
Problem in libvorbis: https://github.com/xiph/vorbis/issues/107

**Comment by bemoody** [comment]
So, this pull request has expanded greatly in scope.

The `darwin.cmake` was broken by the latest libsndfile.  It was apparently passing builds for MacOS *Intel* because it was erroneously linking to some libmpg123.dylib that it found lying around the build environment.

Additionally, I've added a workaround for the vorbis issue.

Meanwhile, on the Linux side: I switched the workflow to building the arm64 library using a cross-compiler on Debian 10 (amd64), rather than running a native compiler on an emulated CPU.  This should be much faster!  I haven't yet tested the resulting binary, and it should be checked (using `auditwheel`?) to make sure it's using the correct ABI for `manylinux_2_28`.

Something is still broken in Windows and I have not begun to dig into that.  My personal inclination would be to use cross-compilation there too.

**Comment by bastibe** [comment]
Wow, that's an extensive set of changes! Thank you so much for looking into this!

**Comment by bastibe** [comment]
Regrettably, cross-compilation doesn't work for Windows, as Python is built with the MSVC compiler, and all linked libraries are required to use the MSVC compiler as well. Clang and GCC can be made to work in some narrow circumstances, but it's just a recipe for headaches. 

I'd guess that, either, there's a bug in the VCPKG build file that will resort itself, or that something about the "-custom" triplet is no longer appropriate.

**Comment by bastibe** [comment]
Do you want to take a stab at the Windows compilation issue as well? No problem at all if not. I'm absolutely grateful for what you have done and achieved so far!

**Pull request merged**
